# _config.yml ─ minimal Jekyll setup for GitHub Pages
title: "**knn_vnsh blog**"
description: "notes/learnings/observations/scratchpad"
url: "https://vanshkhanna.github.io"   # full URL to the site
baseurl: ""                                 # keep empty for username.github.io root
theme: minima                               # GitHub-supported default theme

author:
  name: "**vansh**"
  email: "**~~**"

# Enable the only plugins GitHub Pages builds for you
plugins:
  - jekyll-feed      # automatic RSS
  - jekyll-seo-tag   # better SEO / social cards

# Optional niceties
markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title/
