# _config.yml ─ minimal Jekyll setup for GitHub Pages
title: "vansh's blog"
description: "saas/books/notes"
url: "https://vanshkhanna.github.io"   # full URL to the site
baseurl: ""                                 # keep empty for username.github.io root
remote_theme: "jekyll/minima@1e8a445"


author:
  name: "**vansh**"

# Enable the only plugins GitHub Pages builds for you
plugins:
  - jekyll-remote-theme

# Optional niceties
markdown: kramdown
highlighter: rouge
permalink: /:categories/:year/:month/:day/:title/
